name: Push CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: ./.github/actions/set-up-node

      - name: Run lint
        uses: ./.github/actions/next-lint

      - name: Build
        uses: ./.github/actions/next-build
